### ISSUE TITLE
Unterstützung für UP-Dimmer

### ISSUE THREAD

**Issue by severinbraun** [Bubelbub/RWE-SmartHome-PHP#1]
Hallo,

eine Unterstützung für diese Devices wäre super,
müsste "DimmerActuator" sein.

Viele Grüße ;)

**Comment by Bubelbub** [comment]
Hallo @allmedia,

ich habe derzeit keinen Dimmer bei mir. Weder einen Unterputz noch einen Zwischenstecker.

Mal gucken wie ich das umsetzen kann ;)
Du kannst dann ja ein Tester für den "DimmerActuator" sein.

Gruß,
Bubelbub
